# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"\xd1\x02\n\x07Product\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08\x63\x61tegory\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05price\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x15\n\x08\x64iscount\x18\x06 \x01(\x05H\x05\x88\x01\x01\x12\x15\n\x08quantity\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x12\n\x05\x62rand\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x13\n\x06weight\x18\t \x01(\x02H\x08\x88\x01\x01\x12\x13\n\x06\x65xpiry\x18\n \x01(\tH\t\x88\x01\x01\x42\x05\n\x03_idB\x08\n\x06_titleB\x0e\n\x0c_descriptionB\x0b\n\t_categoryB\x08\n\x06_priceB\x0b\n\t_discountB\x0b\n\t_quantityB\x08\n\x06_brandB\t\n\x07_weightB\t\n\x07_expiryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=18
  _PRODUCT._serialized_end=355
# @@protoc_insertion_point(module_scope)
