# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\xb7\x01\n\tUserModel\x12\x14\n\x07user_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08password\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tfull_name\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x14\n\x07\x61\x64\x64ress\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\n\n\x08_user_idB\x08\n\x06_emailB\x0b\n\t_passwordB\x0c\n\n_full_nameB\n\n\x08_addressb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERMODEL._serialized_start=15
  _USERMODEL._serialized_end=198
# @@protoc_insertion_point(module_scope)
