# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"\xde\x01\n\nOrderModel\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07user_id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x17\n\nproduct_id\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x15\n\x08quantity\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x19\n\x0ctotal_amount\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x13\n\x06status\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\x05\n\x03_idB\n\n\x08_user_idB\r\n\x0b_product_idB\x0b\n\t_quantityB\x0f\n\r_total_amountB\t\n\x07_statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERMODEL._serialized_start=16
  _ORDERMODEL._serialized_end=238
# @@protoc_insertion_point(module_scope)
